name: Summary for profile README

on:
    workflow_dispatch:

    push:
        branches:
            - master
            - develop

    pull_request:
        branches:
            - develop

    schedule:
      - cron: '0 0 1 * *'

jobs:
    compile-readme:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                cache: 'pip'
            
            - run: pip install -r ./requirements.txt

            - name: Generate README
              env:
                GITHUB_TOKEN: ${{ secrets.API_TOKEN }}
              run: python ./gen_readme.py

            - uses: EndBug/add-and-commit@v9
              if: github.ref == 'refs/heads/master'
              with:
                add: 'README.md pages'
                message: 'Update summary'
                default_author: github_actions
                push: true
